#!/bin/bash

# This script simply runs through a directory
# and encodes wrong encodings for pandoc to utf-8
# then converts it into doc in this case
# Finally the tmp utf-8 files are deleted again.

# Yes, this could be much shorter

################
# My variables #
################

# The input encoding
FROM_ENCODING="iso8859-1"

# Convert into encoding (utf-8 for pandoc)
TO_ENCODING="utf-8"

# The input format
FROM_FORMAT="mediawiki"

# The output format
TO_FORMAT="docx"

##################
# My conversions #
##################

# The conversion, //Translit in case you find unkown characters
CONVERT_ENC="iconv -f $FROM_ENCODING -t $TO_ENCODING//TRANSLIT"

# The format conversion
CONVERT_FORM="pandoc -f $FROM_FORMAT -t $TO_FORMAT"

##########################
# The looping over files #
##########################

# Convert the encoding for all mediawiki files and write them into new FILENAME.utf8 files

for file in *.$FROM_FORMAT; do
    $CONVERT_ENC "$file" -o "$file.$TO_ENCODING"
done

# Convert all created UTF-8 files not now to *docx files

# Now loop again to convert this into docx format

for file in *.$TO_ENCODING; do
    $CONVERT_FORM "$file" -o "$file" -o "$file.$TO_FORMAT"
done

# clean up

for file in *.$TO_ENCODING; do
    [ -f "$file" ] && rm "$file"
done

exit 0



01_Buchhaltung.mediawiki.utf-8
